version: '3.4'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
    volumes:
    - D:\postgres:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
    - "6379:6379"
  schoolproject.api:
    image: ${DOCKER_REGISTRY-}schoolprojectapi
    ports:
    - "5000:80"
    depends_on:
    - "postgres"
    - "redis"
    build:
      context: .
      dockerfile: SchoolProject/Dockerfile

networks:
  my-network:
    external: true